
import { basename, dirname, fromFileUrl, join } from "std/path";
import { ensureDirSync } from "std/fs";

import { contains, CustomTypes, Domain, isEmpty, NamingConvention, Orm, resolvePath } from "./preparing.ts";
import { Column, Relation, isMetadata, Metadata } from "./metadata.ts";
import { bold } from "./formatting.ts";


// STANDARD VALUES

const Lib = "litets";

const Notice = "// This file is auto-generated by smake. Do not edit manually.";


// EXPORT FUNCTIONS

const ExportOptions = { create: true, append: false };

export function exportTypes(customTypes: CustomTypes, orm: Orm): TypesMap {
	if (Object.keys(customTypes).length === 0) {
		return {};
	}
	else {
		const [code, typesMap] = generateTypes(customTypes, orm);
		const moduleName = basename(orm.definitionsPath);
		const dir = resolvePath(join(orm.directory, dirname(orm.definitionsPath)));

		ensureDirSync(dir);

		console.log(`Export ORM types module »${moduleName}« to ${bold(dir)}`);
		Deno.writeTextFileSync(join(dir, moduleName), code, ExportOptions);

		return typesMap
	}
}


export function exportClasses(data: Metadata, orm: Orm, typesMap: TypesMap): void {
	const dir = resolvePath(orm.directory);
	const filename = `${data.databaseName}.ts`;

	ensureDirSync(dir);

	console.log(`Export ORM module »${filename}« to ${bold(dir)}`);
	Deno.writeTextFileSync(join(dir, filename), generateClasses(data, orm, typesMap), ExportOptions);
}


// CODE GENERATION FOR TYPE DEFINITIONS

/** Maps each custom type name to its generated TypeScript type and schema identifier. */
export type TypesMap = Record<string, { typeName: string; schemaName: string; }>;


/** Generates type definitions and Zod schemas from custom type definitions; but also returns a mapping of source names to generated TS identifiers. */
export function generateTypes(customTypes: CustomTypes, orm: Orm): [code: string, TypesMap] {
	const i = orm.indent as string;
	const codeLines: string[] = [Notice, ""];
	const withZod = !!orm.zodPath;
	const typesMap: TypesMap = {};

	if (withZod) codeLines.push(`import { z } from "${orm.zodPath}";\n`);

	for (const [name, def] of Object.entries(customTypes)) {
		const typeName = orm.typeNaming ? convertCase(orm.typeNaming, name) : name;
		const schemaName = orm.typeNaming ? convertCase(orm.typeNaming, name + "Schema") : name + "Schema";
		typesMap[name] = { typeName, schemaName };

		codeLines.push("");

		switch (def.affinity) {
			case "TEXT": {
				if (def.values !== undefined) {
					codeLines.push(`export enum ${typeName} {`);
					if (Array.isArray(def.values)) {
						for (const v of def.values as string[])
							codeLines.push(`${i}${v} = ${JSON.stringify(v)},`);
					}
					else {
						for (const [k, v] of Object.entries(def.values))
							codeLines.push(`${i}${k} = ${typeof v === "string" ? JSON.stringify(v) : v},`);
					}
					codeLines.push(`}\n`);
					if (withZod) codeLines.push(`export const ${schemaName} = z.enum(${typeName});\n`);
				}
				else {
					codeLines.push(`export type ${typeName} = string;\n`);
					if (withZod) codeLines.push(`export const ${schemaName} = ${buildTextSchema(def)};\n`);
				}
				break;
			}
			case "NUMERIC":
			case "INTEGER":
			case "REAL": {
				if (def.values !== undefined) {
					if (Array.isArray(def.values)) {
						const vals = def.values as number[];
						codeLines.push(`export type ${typeName} = ${vals.join(" | ")};\n`);
					}
					else {
						codeLines.push(`export enum ${typeName} {`);
						for (const [k, v] of Object.entries(def.values))
							codeLines.push(`${i}${k} = ${v},`);
						codeLines.push(`}\n`);
					}
					if (withZod) codeLines.push(`export const ${schemaName} = ${buildNumericSchema(def)};\n`);
				}
				else {
					codeLines.push(`export type ${typeName} = number;\n`);
					if (withZod) codeLines.push(`export const ${schemaName} = ${buildNumericSchema(def)};\n`);
				}
				break;
			}
			case "BLOB": {
				codeLines.push(`export type ${typeName} = Uint8Array;\n`);
				if (withZod) codeLines.push(`export const ${schemaName} = z.instanceof(Uint8Array);\n`);
				break;
			}
		}
	}

	return [codeLines.join("\n").trimEnd(), typesMap];
}


function buildTextSchema(def: Extract<Domain, { affinity: "TEXT" }>): string {
	let expr = "z.string()";
	if (def.regexp) expr += `.regex(new RegExp(${JSON.stringify(def.regexp)}))`;
	if (def.length !== undefined) expr += `.length(${def.length})`;
	if (def.minLength !== undefined) expr += `.min(${def.minLength})`;
	if (def.maxLength !== undefined) expr += `.max(${def.maxLength})`;
	return expr;
}


function buildNumericSchema(def: Extract<Domain, { affinity: "INTEGER" | "REAL" | "NUMERIC" }>): string {
	if (def.values !== undefined) {
		const vals = (Array.isArray(def.values) ? def.values : Object.values(def.values)) as number[];
		if (vals.length === 1) return `z.literal(${vals[0]})`;
		return `z.union(${JSON.stringify(vals, null, 0).replace(/,/g, ", ")}.map(v => z.literal(v)))`;
	}
	let expr = def.affinity === "INTEGER" ? "z.number().int()" : "z.number()";
	if (def.min !== undefined) expr += `.min(${def.min})`;
	if (def.max !== undefined) expr += `.max(${def.max})`;
	if (def.step !== undefined) expr += `.multipleOf(${def.step})`;
	return expr;
}


// CODE GENERATION FOR CLASS DEFINITIONS

const TypeMap: Record<string, string> = {
	INTEGER: "number",
	BIGINT: "bigint",
	TEXT: "string",
	REAL: "number",
	BLOB: "Uint8Array",
	NUMERIC: "number",
};


const ConstructorMap: Record<string, string> = {
	INTEGER: "Number",
	TEXT: "String",
	REAL: "Number",
	BLOB: "Uint8Array",
	NUMERIC: "Number",
};


/** Generate TypeScript dataclass definitions from SQLite metadata. */
export function generateClasses(data: Metadata, orm: Orm, typesMap: TypesMap): string {
	const i = orm.indent as string;
	const withZod = !!orm.zodPath;
	const codeLines: string[] = [
		Notice,
		`\nimport { Column, TableObject } from "${orm.libraryPath || Lib}";\n`
	];

	if (withZod) codeLines.push(`import { z } from "${orm.zodPath}";\n`)

	if (!isEmpty(typesMap)) {
		const ids = Object.keys(data.usedTypes).flatMap(name => {
			const { typeName, schemaName } = typesMap[name];
			return withZod ? [typeName, schemaName] : [typeName];
		});
		if (ids.length > 0) codeLines.push(`import { ${ids.join(", ")} } from "${orm.definitionsPath}";\n`);
	}

	const objects: [string, Relation][] = [
		...Object.entries(data.tables),
		...(orm.includingViews ? Object.entries(data.views) : []),
	];

	const processName = (s: string): [string, string | null] => {
		const [stripped, suffix] = orm.strippedSuffixes ? stripSuffixes(s, orm.strippedSuffixes) : [s, null];
		return [convertCase(orm.columnNaming, stripped), suffix];
	};

	const tsField = (logical: string, tsType: string, nullable: string, prefix?: string, optional?: boolean): string =>
		`${prefix ? prefix + " " : ""}${logical}${optional ? "?" : ""}: ${tsType}${nullable};`;

	for (const [tableName, obj] of objects) {
		const [className] = processName(tableName);
		const pascalClassName = toPascalCase(className);
		const prefix = data.schemaName;
		const fullName = prefix ? `${prefix}.${tableName}` : tableName;

		const processedCols = Object.entries(obj.columns).map(([phys, info]) => {
			const [logical, suffix] = processName(phys);
			const base = info.affinity.split("(")[0];
			const ctor = ConstructorMap[base] ?? "String";
			const isOptional = info.default !== null || info.nullable || info.generated;
			const tsType = info.isJson
				? "any"
				: info.type && info.type in typesMap
					? typesMap[info.type].typeName
					: (TypeMap[base] ?? "string");
			const nullable = info.nullable ? " | null" : "";
			const hasDefault = info.default !== null || info.generated;
			return { phys, info, logical, suffix, base, ctor, isOptional, tsType, nullable, hasDefault };
		});

		// Interface
		codeLines.push(`\nexport interface ${pascalClassName}Entry {`);
		for (const { logical, tsType, nullable, hasDefault } of processedCols) {
			codeLines.push(`${i}${tsField(logical, tsType, nullable, undefined, hasDefault)}`);
		}
		codeLines.push(`}\n`);

		// Class
		codeLines.push(`export class ${pascalClassName} extends TableObject<${pascalClassName}Entry> {`);
		codeLines.push(`${i}declare static readonly entry: ${pascalClassName}Entry;\n`);
		codeLines.push(`${i}static override readonly schemaName = ${JSON.stringify(prefix ?? "")};`);
		codeLines.push(`${i}static override readonly physicalName = ${JSON.stringify(tableName)};`);
		codeLines.push(`${i}static override readonly fullName = ${JSON.stringify(fullName)};`);
		codeLines.push("");

		for (const { phys, info, logical, ctor, isOptional, tsType, nullable } of processedCols) {
			const colGeneric = `Column<${JSON.stringify(logical)}, ${tsType}${nullable}>`;
			codeLines.push(`${i}static readonly $${logical}: ${colGeneric} = new Column(\n${i}${i}`
				+ `${JSON.stringify(logical)}, `
				+ `${JSON.stringify(phys)}, `
				+ `${pascalClassName}, `
				+ `${ctor}, `
				+ `${info.generated}, `
				+ `${info.nullable}, `
				+ `${isOptional}, `
				+ `${formatDefault(info)}, `
				+ `${info.isJson}`
				+ `\n${i});`);
		}

		codeLines.push("");

		const colRefs = processedCols.map(c => `${pascalClassName}.$${c.logical}`).join(", ");
		const metaEntries = processedCols.map(c => `${c.logical}: ${pascalClassName}.$${c.logical}`).join(", ");
		const uniqueStr = obj.uniqueConstraints
			.map(uc => `[${uc.map(phys => {
				const found = processedCols.find(pc => pc.phys === phys);
				return `${pascalClassName}.$${found?.logical ?? phys}`;
			}).join(", ")}]`)
			.join(", ");
		const physNames = processedCols.map(c => JSON.stringify(c.phys)).join(", ");
		

		codeLines.push(`${i}static override readonly columns: Column[] = [${colRefs}];\n`);
		codeLines.push(`${i}static override readonly metadata: Record<string, Column> = { ${metaEntries} };\n`);
		codeLines.push(`${i}static override readonly uniqueConstraints: Column[][] = [${uniqueStr}];\n`);
		codeLines.push(`${i}static override readonly physicalColumnNames: string[] = [${physNames}];\n`);

		if (withZod) {
			const schemaEntries = processedCols.map(c => `${c.logical}: ${columnSchema(c.info, typesMap)}`).join(", ");
			codeLines.push(`${i}static override readonly schema = z.object({ ${schemaEntries} });`);
		}

		codeLines.push("");

		for (const { logical, tsType, nullable } of processedCols) {
			codeLines.push(`${i}${tsField(logical, tsType, nullable, "declare public")}`);
		}

		codeLines.push("");
		codeLines.push(`${i}constructor(data: Partial<${pascalClassName}Entry> = {}) { super(data as Record<string, unknown>); }`);
		codeLines.push("}\n");
	}

	return codeLines.join("\n").trimEnd();
}


function columnSchema(info: Column, typesMap: TypesMap): string {
	let expr: string;

	if (info.type && info.type in typesMap) {
		expr = typesMap[info.type].schemaName;
	}
	else {
		const base = info.affinity.split("(")[0];
		switch (base) {
			case "INTEGER":
			case "NUMERIC": {
				expr = "z.number().int()";
				break
			};
			case "REAL": {
				expr = "z.number()";
				break
			};
			case "BLOB": {
				expr = "z.instanceof(Uint8Array)";
				break;
			}
			default: {
				expr = "z.string()"
			};
		}
	}

	if (info.nullable) expr += ".nullable()";
	if (info.default !== null) expr += ".optional()";

	return expr;
}


/** Removes suffixes, returning [strippedName, normalizedSuffix]. */
export function stripSuffixes(name: string, suffixes: string[]): [string, string | null] {
	for (const suffix of suffixes) {
		if (name.endsWith(suffix)) {
			const stripped = name.slice(0, -suffix.length).replace(/_+$/, "");
			return [stripped || name, suffix];
		}
	}
	return [name, null];
}


/** Prepare SQLite default value for TS; returns literals, null, or undefined for expressions. */
function formatDefault(info: Column): any {
	let defaultValue;

	if (info.default) {
		if (/^null$/i.test(info.default)) {
			defaultValue = null;
		}
		else {
			switch (info.affinity) {
				case "NUMERIC":
				case "INTEGER":
				case "REAL": {
					defaultValue = /^-?\d+(\.\d+)?$/.test(info.default) ? Number(info.default) : undefined;
					break;
				}
				case "TEXT": {
					if (info.default.startsWith("'") && info.default.endsWith("'")) {
						defaultValue = JSON.stringify(info.default.slice(1, -1));
					}
					break;
				}
				default:
					break;
			}
		}
	}

	return defaultValue;
}


// CONVERTING NAMES TO DIFFERENT CASES

export function toSnakeCase(name: string): string {
	return name.replace(/([a-z])([A-Z])/g, "$1_$2").replace(/\s+/g, "_").toLowerCase();
}

export function toCamelCase(name: string): string {
	return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

export function toPascalCase(name: string): string {
	return name[0].toUpperCase() + name.slice(1);
}

export function toNormalCase(name: string): string {
	return name.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ").toLowerCase();
}


export function convertCase(convention: NamingConvention, name: string): string {
	switch (convention) {
		case "PascalCase":
			return toPascalCase(name);
		case "camelCase":
			return toCamelCase(name);
		case "snake_case":
			return toSnakeCase(name);
	}
}
